language: node_js
node_js:
    - 12

services:
  - docker

before_install:
  #install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - docker build -t registry.heroku.com/eonhetest/web .

deploy:
  provider: script
  script:
    bash docker_push
  on:
    branch: scotty_hesmt

# safelist
branches:
  only:
  - master
  - scotty_hesmt
